Feature/pits 6
anyanyaa/project-x pull request #16
Opened 2022-04-22 09:17 UTC by anyabuu

[PITS-](https://rammfall.atlassian.net/browse/PITS-)

### Description
сделала верстку страницы и адаптивку, есть нюанс, подвисла на background image, они выходят поверх карточек

2022-04-22 20:41 UTC, Rammfall requested changes

2022-04-22 20:41 UTC, Rammfall commented on src/scss/pages/promotions/promo-cards.scss
> +  margin-top: -40px;
А зачем здесь отрицательный маржин?

2022-04-22 20:41 UTC, Rammfall commented on src/scss/pages/promotions/promo-cards.scss
> +    justify-content: space-evenly;
Уверена что нужен именно space-evenly а не space-between?

2022-04-22 20:41 UTC, Rammfall commented on src/scss/pages/promotions/promo-cards.scss
> +  width: 100%;
Супер, молодец!

2022-04-23 07:04 UTC, anyabuu commented on src/scss/pages/promotions/promo-cards.scss
> +  margin-top: -40px;
У меня на hero навешен padding-bottom, а hero для всех общий, и чтобы его не менять на каждую страницу, я его убираю минусовыми маржинами)

2022-04-23 07:07 UTC, anyabuu commented on src/scss/pages/promotions/promo-cards.scss
> +    justify-content: space-evenly;
да, точно, я поменяла размер карточек а это забыла

2022-04-23 07:45 UTC, Rammfall approved these changes

2022-04-23 07:46 UTC, Rammfall commented
Можешь мержить, не забудь перед этим нажать update branch  и обновить ветку

2022-04-23 10:58 UTC, merged