Feature/pits 7
anyanyaa/project-x pull request #17
Opened 2022-04-24 17:52 UTC by anyabuu

[PITS-](https://rammfall.atlassian.net/browse/PITS-)

### Description

Готовая страница с адаптивкой, не уверена насчет правильности функционала кнопок reset/submit и насчет инпутов, чтобы они потом нормально работали с js-ом)

2022-05-02 15:54 UTC, Rammfall requested changes

2022-05-02 15:54 UTC, Rammfall commented on src/scss/general.scss
> +  --color-back-text: #9d9d9b;
Я эти моменты упустил, но сейчас обратил внимание. Цвета хорошо называть не по элементу в котором они находятся, а как-то абстрактно. Конечно трудновато это полноценно сделать в таком проекте, но лучше всем давать названия типа primary-color, secondary и тд. Даже не оч круто называть по цвету, ибо color-blue например, у нас может меняться тема(темная и светлая) и название будет не актуальным

2022-05-02 15:54 UTC, Rammfall commented on src/scss/mixins.scss
> +}
Смотри, миксины лучше использовать для каких-то мелких кусочков, но не стоит описывать полностью компонент так, лучше перенести эти стили в селектор и использовать только этот селектор для элемента, ибо вероятность что нам будет ещё один компонент с точно такими стилями минимальна. Миксины это удобные кусочки(типографика, флексы, тени), но не компоненты

2022-05-02 15:54 UTC, Rammfall commented on src/cabinet.html
> +    <form class="profile__form" action="" method="post">
Давай файл назовем profile, а то кабинет это транслит)

2022-05-06 00:19 UTC, Rammfall requested changes

2022-05-06 00:19 UTC, Rammfall commented on src/cabinet.html
> +        <li class="profile__list-item">
Это всё таки не лишка, и не список, когда форма, они редко бывают списками
И по БЭМу я бы выделил в отдельный блок это всё, ибо они будут использоваться на других страницах

2022-05-06 09:44 UTC, anyabuu commented on src/cabinet.html
> +        <li class="profile__list-item">
по поводу БЭМа и отдельного блока не совсем поняла - целую форму вынести в блок? у нас же кроме инпута имени и номера телефона ничего дальше не повторяется, там другие типы инпутов, да и позиционирования элементов тут особого нет
а кнопки и элементы формы у нас уже есть в отдельных компонентах, чтобы потом из них собирать формы

2022-05-06 14:44 UTC, Rammfall commented on src/cabinet.html
> +        <li class="profile__list-item">
Понял, оки, но давай эту штуку не делать списком, это просто форма, их обычно не нужно делать списками, они функциональные элементы. А так тогда ок)

2022-05-06 19:38 UTC, anyabuu commented on src/cabinet.html
> +        <li class="profile__list-item">
хорошо) это сделала)

2022-05-07 16:33 UTC, Rammfall approved these changes

2022-05-07 16:59 UTC, merged