Homepage/promo
anyanyaa/project-x pull request #4
Opened 2022-04-03 20:12 UTC by anyabuu

2022-04-03 22:18 UTC, Rammfall requested changes

2022-04-03 22:18 UTC, Rammfall commented on src/css/styles.css
> +<<<<<<< HEAD
Такс, ты не зарезолвила все конфликты, видимо от этого верстка и немного поломалась, исправь пожалуйста

2022-04-03 22:18 UTC, Rammfall commented on src/css/styles.css
> +=======
Вот ещё гитовые комменты, этот файл нужно удалить и закомитить его удаление

2022-04-03 22:30 UTC, Rammfall requested changes

2022-04-03 22:30 UTC, Rammfall commented on src/index.html
> +        <div class="promo__card-group">
Это список

2022-04-03 22:30 UTC, Rammfall commented on src/index.html
> +          <img class="promo__big-image" src="img/promo.jpg" alt="this is our promo">
Это также обернуто ссылкой, как и нижние его коллеги

2022-04-04 19:21 UTC, anyabuu commented on src/index.html
> +        <div class="promo__card-group">
я поменяла тут на список, но так как внутри ul нельзя вставлять div, а большую картинку нужно было как то изолировать, я сделала гридами и через nth child)
может быть усложнила? как то можно было оставить на флексах или так тоже нормально?

2022-04-04 21:23 UTC, Rammfall approved these changes

2022-04-04 21:23 UTC, merged